version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 8888:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalcar
    volumes:
      - pgdata:/data/postgres 

  app:
    build: .
    container_name: rentalcar
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes: 
  pgdata:
    driver: local